// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZ_WEZL1yJX0qLbS-jePGkk_wdZLLwlGQ',
    appId: '1:654771838843:web:b3ccaba3eb6db9a515a7de',
    messagingSenderId: '654771838843',
    projectId: 'e-chat-app-7d68b',
    authDomain: 'e-chat-app-7d68b.firebaseapp.com',
    storageBucket: 'e-chat-app-7d68b.firebasestorage.app',
    measurementId: 'G-9GL76MPNLF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbwsbVOcZ1QON1TZBfz8nUOA0fTAKYeSU',
    appId: '1:654771838843:android:018bdcff0a6c975c15a7de',
    messagingSenderId: '654771838843',
    projectId: 'e-chat-app-7d68b',
    storageBucket: 'e-chat-app-7d68b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC95LK4bulXUSIbPoaV2SFe6vhDVogH9vk',
    appId: '1:654771838843:ios:33f72792fd901b7715a7de',
    messagingSenderId: '654771838843',
    projectId: 'e-chat-app-7d68b',
    storageBucket: 'e-chat-app-7d68b.firebasestorage.app',
    iosBundleId: 'com.example.chattingapp',
  );
}
